import { CaptionLine, CaptionStyleMeta } from "./types";

export const SAMPLE_CAPTION_LINES: CaptionLine[] = [
  {
    id: "line-1",
    startMs: 0,
    endMs: 1900,
    tokens: [
      { text: "Welcome", fromMs: 0, toMs: 450 },
      { text: "to", fromMs: 450, toMs: 700 },
      { text: "Planet", fromMs: 700, toMs: 1100 },
      { text: "in", fromMs: 1100, toMs: 1350 },
      { text: "Pixel.", fromMs: 1350, toMs: 1850 },
    ],
    fullText: "Welcome to Planet in Pixel.",
  },
  {
    id: "line-2",
    startMs: 1950,
    endMs: 4100,
    tokens: [
      { text: "India's", fromMs: 1950, toMs: 2400 },
      { text: "best", fromMs: 2400, toMs: 2750 },
      { text: "Video", fromMs: 2750, toMs: 3150 },
      { text: "Editing", fromMs: 3150, toMs: 3600 },
      { text: "School.", fromMs: 3600, toMs: 4050 },
    ],
    fullText: "India's best Video Editing School.",
  },
  {
    id: "line-3",
    startMs: 4150,
    endMs: 6500,
    tokens: [
      { text: "Its", fromMs: 4150, toMs: 4450 },
      { text: "for", fromMs: 4450, toMs: 4750 },
      { text: "Content", fromMs: 4750, toMs: 5200 },
      { text: "creators,", fromMs: 5200, toMs: 5700 },
      { text: "Video", fromMs: 5700, toMs: 6050 },
      { text: "Editors", fromMs: 6050, toMs: 6500 },
    ],
    fullText: "Its for Content creators, Video Editors",
  },
];

export const TOTAL_DURATION_FRAMES = 195; // 6.5s @ 30fps

export const CAPTION_STYLES_META: CaptionStyleMeta[] = [
  // ==========================================
  // CATEGORY 1: KEYWORD EMPHASIS (STYLES 1 - 2)
  // ==========================================
  {
    number: 1,
    id: "emphasis-gradient-duo",
    slug: "emphasis-gradient-duo",
    name: "01 - Bold White + Italic Sunset Gradient",
    category: "Keyword Emphasis",
    fontFamily: "'Inter', sans-serif",
    description: "Entire line at once with key words highlighted in an energetic italic pink-to-blue gradient",
    badgeColor: "#EC4899",
  },
  {
    number: 2,
    id: "emphasis-serif-cyan",
    slug: "emphasis-serif-cyan",
    name: "02 - Modern Sans + Cyan Italic Serif",
    category: "Keyword Emphasis",
    fontFamily: "'Inter' + 'Playfair Display'",
    description: "Entire line at once with key words highlighted in an elegant glowing electric cyan italic serif",
    badgeColor: "#00C2FF",
  },

  // ==========================================
  // CATEGORY 2: STATIC FULL-LINE (STYLES 3 - 7)
  // ==========================================
  {
    number: 3,
    id: "static-frost-charcoal-pill",
    slug: "static-frost-charcoal-pill",
    name: "03 - Frosted Charcoal Rounded Box",
    category: "Static Full-Line",
    fontFamily: "'Sora', sans-serif",
    description: "Static silver frost text in a sleek dark charcoal frosted glass box with rounded corners",
    badgeColor: "#38BDF8",
  },
  {
    number: 4,
    id: "static-neon-cyan-pill",
    slug: "static-neon-cyan-pill",
    name: "04 - Cyber Glass Rounded Box",
    category: "Static Full-Line",
    fontFamily: "'Orbitron', sans-serif",
    description: "Static electric cyan full-line text in curved glass box with neon glow",
    badgeColor: "#00F0FF",
  },
  {
    number: 5,
    id: "static-crimson-pill",
    slug: "static-crimson-pill",
    name: "05 - Velvet Crimson Rounded Box",
    category: "Static Full-Line",
    fontFamily: "'Poppins', sans-serif",
    description: "Static crisp white text inside a curved rich crimson-rose velvet box",
    badgeColor: "#F43F5E",
  },
  {
    number: 6,
    id: "static-editorial-vogue",
    slug: "static-editorial-vogue",
    name: "06 - Vogue Line & Golden Rule",
    category: "Static Full-Line",
    fontFamily: "'Cormorant Garamond', serif",
    description: "Instant luxury editorial sand-ivory line with delicate golden underline rule",
    badgeColor: "#F5EBE0",
  },
  {
    number: 7,
    id: "static-broadcast-clean",
    slug: "static-broadcast-clean",
    name: "07 - Netflix Doc Subtitle",
    category: "Static Full-Line",
    fontFamily: "'DM Sans', sans-serif",
    description: "High-contrast sunshine yellow static line with crisp stroke outline for maximum clarity",
    badgeColor: "#FFD200",
  },

  // ==========================================
  // CATEGORY 3: UNIFORM (STYLES 8 - 12)
  // ==========================================
  {
    number: 8,
    id: "uniform-swiss-chalk",
    slug: "uniform-swiss-chalk",
    name: "08 - Swiss Editorial Minimal",
    category: "Uniform",
    fontFamily: "'Inter', sans-serif",
    description: "Ultra-clean chalk white typography with wide tracking and pure line crossfades",
    badgeColor: "#FFFFFF",
  },
  {
    number: 9,
    id: "uniform-vintage-sepia",
    slug: "uniform-vintage-sepia",
    name: "09 - 16mm Vintage Bolex Box",
    category: "Uniform",
    fontFamily: "'Cormorant Garamond', serif",
    description: "Warm amber sepia cream text on dark chocolate vignette with fine grain border",
    badgeColor: "#FDF6E2",
  },
  {
    number: 10,
    id: "uniform-cyber-emerald",
    slug: "uniform-cyber-emerald",
    name: "10 - Tactical Phosphor HUD",
    category: "Uniform",
    fontFamily: "'Fira Code', monospace",
    description: "Uniform glowing phosphor emerald green on dark tactical glass with HUD corner reticles",
    badgeColor: "#00FF88",
  },
  {
    number: 11,
    id: "uniform-tokyo-orchid",
    slug: "uniform-tokyo-orchid",
    name: "11 - Tokyo Neo Orchid Box",
    category: "Uniform",
    fontFamily: "'Outfit', sans-serif",
    description: "Electric orchid/lavender text in a curved dark violet glass capsule with neon border",
    badgeColor: "#E879F9",
  },
  {
    number: 12,
    id: "uniform-hollywood-gold",
    slug: "uniform-hollywood-gold",
    name: "12 - Golden Age Art Deco",
    category: "Uniform",
    fontFamily: "'Marcellus', serif",
    description: "24k old Hollywood solid gold Roman serif with geometric Art Deco double border",
    badgeColor: "#FFD700",
  },

  // ==========================================
  // CATEGORY 4: CINEMATIC SLIDE (STYLES 13 - 17)
  // ==========================================
  {
    number: 13,
    id: "cinematic-tungsten",
    slug: "cinematic-tungsten",
    name: "13 - 70mm Tungsten Gold",
    category: "Cinematic",
    fontFamily: "'Cinzel', serif",
    description: "IMAX 70mm title aesthetic with golden letterbox brackets and slow vertical glide",
    badgeColor: "#F59E0B",
  },
  {
    number: 14,
    id: "cinematic-nordic-frost",
    slug: "cinematic-nordic-frost",
    name: "14 - Nordic Arthouse Frost",
    category: "Cinematic",
    fontFamily: "'Tenor Sans', sans-serif",
    description: "A24-inspired minimalist frosted glass bar with glacial blue upward flow",
    badgeColor: "#93C5FD",
  },
  {
    number: 15,
    id: "cinematic-bladerunner",
    slug: "cinematic-bladerunner",
    name: "15 - Anamorphic Teal & Gold",
    category: "Cinematic",
    fontFamily: "'Sora', sans-serif",
    description: "Neo-noir cinematic crosshair reticles with atmospheric focus blur & slow slide",
    badgeColor: "#2DD4BF",
  },
  {
    number: 16,
    id: "cinematic-champagne",
    slug: "cinematic-champagne",
    name: "16 - Haute Couture Editorial",
    category: "Cinematic",
    fontFamily: "'Playfair Display', serif",
    description: "Luxury Italian editorial with champagne gold jewelry border & poetic rise",
    badgeColor: "#D4AF37",
  },
  {
    number: 17,
    id: "cinematic-ethereal",
    slug: "cinematic-ethereal",
    name: "17 - Deep Space Monolith",
    category: "Cinematic",
    fontFamily: "'Space Grotesk', sans-serif",
    description: "Kubrick/Interstellar wide spaced monolithic pillars with gravitational float",
    badgeColor: "#C084FC",
  },

  // ==========================================
  // CATEGORY 5: POP & CREATIVE (STYLES 18 - 28)
  // ==========================================
  {
    number: 18,
    id: "sunset-gradient",
    slug: "sunset-gradient",
    name: "18 - Sunset Wave Gradient",
    category: "Pop & Animated",
    fontFamily: "'Outfit', sans-serif",
    description: "Multi-stop coral to gold gradient text with smooth shimmer glow on active words",
    badgeColor: "#FF7E5F",
  },
  {
    number: 19,
    id: "viral-pop",
    slug: "viral-pop",
    name: "19 - Viral Pop (TikTok/Reels)",
    category: "Pop & Animated",
    fontFamily: "'Montserrat', sans-serif",
    description: "High-energy word-by-word yellow pop scale animation for Shorts & Reels",
    badgeColor: "#FFE600",
  },
  {
    number: 20,
    id: "curved-pill",
    slug: "curved-pill",
    name: "20 - Curved Cyan Box",
    category: "Pop & Animated",
    fontFamily: "'Poppins', sans-serif",
    description: "Clean dark glass rounded box with electric cyan active word pop",
    badgeColor: "#00E5FF",
  },
  {
    number: 21,
    id: "cinema-minimal",
    slug: "cinema-minimal",
    name: "21 - Cinema Minimal Subtitle",
    category: "Pop & Animated",
    fontFamily: "'Playfair Display', serif",
    description: "Subtle golden underline indicator on active spoken words",
    badgeColor: "#F5D77F",
  },
  {
    number: 22,
    id: "neon-cyberpunk",
    slug: "neon-cyberpunk",
    name: "22 - Neon Cyberpunk Glow",
    category: "Pop & Animated",
    fontFamily: "'Orbitron', sans-serif",
    description: "Hot pink neon glow badge on active spoken words with cyber cyan base",
    badgeColor: "#FF007F",
  },
  {
    number: 23,
    id: "sticker-badge",
    slug: "sticker-badge",
    name: "23 - Sticker Word Badge",
    category: "Pop & Animated",
    fontFamily: "'Inter', sans-serif",
    description: "Steady horizontal neon lime sticker plate behind active words",
    badgeColor: "#CCFF00",
  },
  {
    number: 24,
    id: "terminal-code",
    slug: "terminal-code",
    name: "24 - Terminal / Hacker Code",
    category: "Pop & Animated",
    fontFamily: "'Fira Code', monospace",
    description: "Amber matrix monospace with character typewriter reveal and blinking cursor",
    badgeColor: "#FFB000",
  },
  {
    number: 25,
    id: "frosted-glass",
    slug: "frosted-glass",
    name: "25 - Frosted Glass Box",
    category: "Pop & Animated",
    fontFamily: "'Inter', sans-serif",
    description: "Apple-inspired frosted glass box with pristine uniform typography",
    badgeColor: "#A5B4FC",
  },
  {
    number: 26,
    id: "comic-3d",
    slug: "comic-3d",
    name: "26 - Comic 3D Pop",
    category: "Pop & Animated",
    fontFamily: "'Bangers', cursive",
    description: "Deep 3D extruded drop shadows with energetic spring overshoot pop",
    badgeColor: "#FF6B6B",
  },
  {
    number: 27,
    id: "marker-brush",
    slug: "marker-brush",
    name: "27 - Marker Brush Lettering",
    category: "Pop & Animated",
    fontFamily: "'Permanent Marker', cursive",
    description: "Hand-drawn marker font with organic scale bounce",
    badgeColor: "#FF70A6",
  },
  {
    number: 28,
    id: "newsroom-split",
    slug: "newsroom-split",
    name: "28 - Newsroom Split Box",
    category: "Pop & Animated",
    fontFamily: "'Barlow Condensed', sans-serif",
    description: "Heavy broadcast documentary boxed plates with red live indicator tag",
    badgeColor: "#EF4444",
  },
];
